branches:
    only:
        - master
        - /^greenkeeper/.*$/

language: node_js
node_js:
    - lts/*
cache:
    directories:
        - node_modules

install:
    - npm install
script:
    - npm run build
deploy:
    provider: pages
    on:
        branch: master
    skip_cleanup: true
    local_dir: dist/
    # fqdn: ${DOMAIN}        # Custom Domain
    # target_branch: master  # namespace/namespace.github.io needs this
    token: ${TOKEN}
